export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGN_OUT = 'SIGN_OUT';
export const FETCH_MESSAGE='FETCH_MESSAGE';
export const UPDATE_USER='UPDATE_USER';
export const UPLOAD_PICTURE='UPLOAD_PICTURE';
export const FETCH_USERS='FETCH_USERS';
export const SINGLE_USER='SINGLE_USER';
export const CATEGORY_USERS='CATEGORY_USERS';
export const ROOT_URL='http://ec2-54-153-123-125.us-west-1.compute.amazonaws.com/'
